import {FC} from 'react';
import {SvgProps} from 'react-native-svg';

export type IconsType = Record<string, FC<SvgProps>>;

export {default as PlusSquared} from './plus-squared.svg';
export {default as Rectangle} from './rectangle.svg';
export {default as Pen} from './pen.svg';
export {default as Cross} from './cross.svg';
export {default as Arrow} from './arrow.svg';
export {default as ArrowDown} from './arrow-down.svg';
export {default as UserIcon} from './user.svg';
export {default as HomeIcon} from './home.svg';
export {default as BudgetIcon} from './pie-chart.svg';
export {default as Settings} from './settings.svg';
export {default as TransactionIcon} from './transaction.svg';
export {default as Plus} from './plus-filled.svg';
export {default as Dots} from './dots.svg';
export {default as HideEye} from './hide_eye.svg';
export {default as Eye} from './eye.svg';
export {default as Clocks} from './clocks.svg';
export {default as User} from './user.svg';
export {default as ProfileIcon} from './profile.svg';
export {default as Bank} from './bank.svg';
export {default as Upload} from './pen.svg';
export {default as Camera} from './plus-squared.svg';
export {default as Logo} from './omni-logo.svg';
export {default as CreditCard} from './credit-card.svg';
export {default as FileCheck} from './file-check.svg';
export {default as ArrowsDownUp} from './arrow-down-up.svg';
export {default as Phone} from './phone.svg';
